### ISSUE TITLE
URL to accepting collegeboard's terms and conditions redirects

### ISSUE THREAD

**Issue by andrea-phet** [abalabahaha/apscores#1]
Hi! First of all, thank you so much for making this website. It is so helpful.

For some people, (I think the ones who are trying to get their AP scores for the first time) they receive this error message on the website: You must accept CollegeBoard terms and conditions: https://apscore.collegeboard.org/scores/viewTermsAndConditions.action.

But when you put that URL into the browser, it redirects to http://www.apscore.org/schedule.html#NA.

Is there a workaround for this?

**Comment by abalabahaha** [comment]
Yeah, I pushed a fix that should pop up a dialog to accept terms and conditions.

If you don't see this, try refreshing a few times, or go to Incognito Mode/Private Browsing

**Comment by andrea-phet** [comment]
It worked!
